<?xml version="1.0"?>
<?xml-model href="http://download.ros.org/schema/package_format3.xsd" schematypens="http://www.w3.org/2001/XMLSchema"?>
<package format="3">
  <name>ur7e_bringup</name>
  <version>0.1.0</version>
  <description>Launch files, configurations, and URDF for the UR7e operation system.</description>
  <maintainer email="you@example.com">Your Name</maintainer>
  <license>MIT</license>

  <buildtool_depend>ament_cmake</buildtool_depend>

  <exec_depend>ur_robot_driver</exec_depend>
  <exec_depend>ur_description</exec_depend>
  <exec_depend>moveit_ros_planning_interface</exec_depend>
  <exec_depend>realsense2_camera</exec_depend>
  <exec_depend>robot_state_publisher</exec_depend>
  <exec_depend>joint_state_publisher</exec_depend>
  <exec_depend>rviz2</exec_depend>
  <exec_depend>xacro</exec_depend>

  <exec_depend>ur7e_camera_vision</exec_depend>
  <exec_depend>ur7e_motion</exec_depend>
  <exec_depend>ur7e_play_operation</exec_depend>

  <export>
    <build_type>ament_cmake</build_type>
  </export>
</package>
